force-app/main/default/objects/ClaimHeader__c/ClaimHeader__c.object-meta.xml
<CustomObject>
    <description>Contains summary information about the claim, such as the payment amount, specified medications, and billing data. </description>
    <label>ClaimHeader</label>
    <nameField>
        <displayFormat>21{0000000000}</displayFormat>
        <label>ClaimNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ClaimHeader</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClaimHeader__c/fields/ClaimStatusId__c.field-meta.xml
<CustomField>
    <fullName>ClaimStatusId__c</fullName>
    <inlineHelpText>Current status of the claim.</inlineHelpText>
    <label>ClaimStatusId</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Global_Claim_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimLine__c/ClaimLine__c.object-meta.xml
<CustomObject>
    <description>Represents a line item in a claim record.</description>
    <label>ClaimLine</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClaimLine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClaimLine__c/fields/ClaimId__c.field-meta.xml
<CustomField>
    <fullName>ClaimId__c</fullName>
    <inlineHelpText>ID of the claim that this record is related to.</inlineHelpText>
    <label>ClaimId</label>
    <referenceTo>ClaimHeader__c</referenceTo>
    <relationshipLabel>ClaimLine</relationshipLabel>
    <relationshipName>ClaimIdonClaimLine</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClaimLine__c/fields/ClaimStatusId__c.field-meta.xml
<CustomField>
    <fullName>ClaimStatusId__c</fullName>
    <inlineHelpText>ID of the claim status that this record is related to.</inlineHelpText>
    <label>ClaimStatusId</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Global_Claim_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimLine__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <inlineHelpText>Service start date for claim line.</inlineHelpText>
    <label>From</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ClaimLine__c/fields/ProcedureCPTHCPCSId__c.field-meta.xml
<CustomField>
    <fullName>ProcedureCPTHCPCSId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Service procedure code based on Current Procedural Terminology (CPT) or Healthcare Common Procedure Coding System (HCPCS).</inlineHelpText>
    <label>ProcedureCPTHCPCSId</label>
    <referenceTo>HealthCare_Procedure__c</referenceTo>
    <relationshipLabel>ClaimLine</relationshipLabel>
    <relationshipName>ClaimLineProcedure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ClaimLine__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <inlineHelpText>Service end date for claim line.</inlineHelpText>
    <label>To</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ClaimLine__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <inlineHelpText>Number of units of service or drug provided to the patient.</inlineHelpText>
    <label>Unit</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ClaimLineSearchController.cls
public class ClaimLineSearchController{
    @AuraEnabled
    public static List <ClaimLine__c> fetchClaimLines(String searchTerm) {
        //Qyery 10 accounts
        //System.debug('Hello World!');
        System.debug('The Search which has satisfied the condition '+searchTerm);
        //String modifiedSearchTerm = '%'+searchTerm+'%';
        //System.debug('The Modified Search which has satisfied the condition '+modifiedSearchTerm);
        List<ClaimLine__c> clainLine = [SELECT Name, ClaimId__c, 
                                        ClaimStatusId__c, From__c , To__c, 
                                        ProcedureCPTHCPCSId__c , 
                                        Unit__c , 
                                        Price__c 
                                        FROM ClaimLine__c
                                        WHERE ClaimId__c IN (SELECT  Id
                                                             FROM ClaimHeader__c
                                                             WHERE Name=:searchTerm)];
        //return list of accounts
        return clainLine;
    }
}