force-app/main/default/objects/ClaimDiagnosis__c/ClaimDiagnosis__c.object-meta.xml
<CustomObject>
    <description>Represents the clinical diagnosis for which the service, equipment, or medication was provided.</description>
    <label>ClaimDiagnosis</label>
    <nameField>
        <label>Diagnosis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClaimDiagnosis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClaimDiagnosis__c/fields/ClaimId__c.field-meta.xml
<CustomField>
    <fullName>ClaimId__c</fullName>
    <inlineHelpText>ID of the claim that this record is related to.</inlineHelpText>
    <label>ClaimId</label>
    <referenceTo>ClaimHeader__c</referenceTo>
    <relationshipLabel>ClaimDiagnosis</relationshipLabel>
    <relationshipName>ClaimDiagnosisLineofClaimId</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClaimDiagnosis__c/fields/Diagnosis_Code__c.field-meta.xml
<CustomField>
    <fullName>Diagnosis_Code__c</fullName>
    <formula>Diagnosis__r.Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Diagnosis Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ClaimDiagnosis__c/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <inlineHelpText>Claim diagnosis ID number.</inlineHelpText>
    <label>Line Number</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimHeader__c/ClaimHeader__c.object-meta.xml
<CustomObject>
    <description>Contains summary information about the claim, such as the payment amount, specified medications, and billing data. </description>
    <label>ClaimHeader</label>
    <nameField>
        <displayFormat>21{0000000000}</displayFormat>
        <label>ClaimNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ClaimHeader</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ClaimHeader__c/fields/ClaimStatusId__c.field-meta.xml
<CustomField>
    <fullName>ClaimStatusId__c</fullName>
    <inlineHelpText>Current status of the claim.</inlineHelpText>
    <label>ClaimStatusId</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Global_Claim_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimLine__c/ClaimLine__c.object-meta.xml
<CustomObject>
    <description>Represents a line item in a claim record.</description>
    <label>ClaimLine</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ClaimLine</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ClaimLine__c/fields/ClaimId__c.field-meta.xml
<CustomField>
    <fullName>ClaimId__c</fullName>
    <inlineHelpText>ID of the claim that this record is related to.</inlineHelpText>
    <label>ClaimId</label>
    <referenceTo>ClaimHeader__c</referenceTo>
    <relationshipLabel>ClaimLine</relationshipLabel>
    <relationshipName>ClaimIdonClaimLine</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ClaimLine__c/fields/ClaimStatusId__c.field-meta.xml
<CustomField>
    <fullName>ClaimStatusId__c</fullName>
    <inlineHelpText>ID of the claim status that this record is related to.</inlineHelpText>
    <label>ClaimStatusId</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Global_Claim_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimLine__c/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <inlineHelpText>Claim line ID number.</inlineHelpText>
    <label>LineNumber</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ClaimLine__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <inlineHelpText>Location details of the place where service was performed.</inlineHelpText>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>POS_Point_of_Service</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ClaimLine__c/fields/ProcedureCPTHCPCSId__c.field-meta.xml
<CustomField>
    <fullName>ProcedureCPTHCPCSId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Service procedure code based on Current Procedural Terminology (CPT) or Healthcare Common Procedure Coding System (HCPCS).</inlineHelpText>
    <label>ProcedureCPTHCPCSId</label>
    <referenceTo>HealthCare_Procedure__c</referenceTo>
    <relationshipLabel>ClaimLine</relationshipLabel>
    <relationshipName>ClaimLineProcedure</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HealthCare_Procedure__c/HealthCare_Procedure__c.object-meta.xml
<CustomObject>
    <label>HealthCare Procedure</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HealthCare Procedure</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ClaimViewController.cls
public with sharing class ClaimViewController {
    @AuraEnabled
    public static ClaimHeader__c getClaimHeaderId (String claimName) {
        return [
        SELECT Id
        FROM ClaimHeader__c
        WHERE Name = :claimName
        WITH SECURITY_ENFORCED
        LIMIT 1
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<ClaimLine__c> getClaimLineList(String ClaimId) {
        return [
            SELECT Id, Name, ProcedureCPTHCPCSId__r.Name, ClaimStatusId__c, Location__c, Price__c 
            FROM ClaimLine__c
            WHERE ClaimId__c = :ClaimId
            WITH SECURITY_ENFORCED
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<ClaimDiagnosis__c> getClaimDiagnosisList(String ClaimId) {
        return [
            SELECT Id, Name, LineNumber__c, Diagnosis_Code__c 
            FROM ClaimDiagnosis__c
            WHERE ClaimId__c = :ClaimId
            WITH SECURITY_ENFORCED
        ];
    }
}